CREATE TABLE POLL_OPTION
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    POLL_ID         BIGINT NOT NULL,
    TEXT            VARCHAR(255) NOT NULL UNIQUE
);

ALTER TABLE POLL_OPTION
    ADD FOREIGN KEY (POLL_ID)
    REFERENCES POLL(ID);

CREATE UNIQUE INDEX PK_PO_PID_TEXT ON POLL_OPTION
(
  POLL_ID, TEXT
);