CREATE TABLE POLL
(
    ID              BIGINT AUTO_INCREMENT PRIMARY KEY,
    INITIATOR       BIGINT NOT NULL,
    TITLE           VARCHAR(255) NOT NULL,
    INITIATED       BIGINT NOT NULL,
    LATEST_CHANGE   BIGINT NOT NULL
);

ALTER TABLE POLL
    ADD FOREIGN KEY (INITIATOR)
    REFERENCES USER(ID);